# Experimental/WIP CI build (attempting to migrate from Travis CI)
name: WIP CI build

on:
  push:
    branches: [ release/3.x ]
  pull_request:
    branches: [ release/3.x ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 14]

    steps:
    - uses: actions/checkout@v2 # https://github.com/actions/checkout
      with:
        fetch-depth: 100 # just enough to get recent tags and commits
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build
      run: ./gradlew build -x animalSnifferMain
